version: '3'

services:
  web:
    build:
      context: .
    ports:
      - "80:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - .env  # You can use an environment file to manage your Django project settings



  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
